name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 'Sanjana'
          password: 'dckr_pat_OOEfWUfwG6BcENTjVr-SSJvt2WU'



# name: Checks

# on:
#   push:
#     branches:
#       - main  # Adjust this to the branch you want to trigger the workflow on

# jobs:
#   test-lint:
#     name: Test and Lint
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
        

#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set Environment Variables
#         run: |
#           echo "::set-env name=isPost::$(grep -E '^isPost=' .env | cut -d '=' -f2-)"
#           echo "::set-env name=registry::$(grep -E '^registry=' .env | cut -d '=' -f2-)"
#           echo "::set-env name=logout::$(grep -E '^logout=' .env | cut -d '=' -f2-)"
#           echo "Environment variables set."

#       - name: Run Tests
#         run: |
#           docker-compose run --rm app sh -c "python manage.py test"

#       - name: Run Linter
#         run: |
#           docker-compose run --rm app sh -c "flake8"
