name: Checks

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    env:
        username: 'Sanjana'
        password: 'dckr_pat_OOEfWUfwG6BcENTjVr-SSJvt2WU'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter
        run: |
          docker-compose run --rm app sh -c "flake8"
